### ISSUE TITLE
Audio Files didn't get moved to Cloud

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#121]
Destiny have reported an issue with two sermons that the audio file didn't get moved to Cloud, do we know why?

**Comment by JNaismith** [comment]
Sort of. There were three files in all that didn't get moved to cloud:
 - Two of them were "uploaded" on the 18th of August, and there are no logs that give any indication of what exactly went wrong. However, the database also suggests that ID3 Tagging didn't work for those files either, so I'm thinking that an ID3 tag failure may have something to do with it.
 - The other file was because of the uppercase issue of the Codeigniter Update. That was fixed in the pull request made on Monday.

**Comment by andrewmfraser** [comment]
We'll monitor this, closing for now.
